[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
testpaths = tests
pythonpath = .
addopts = -q --reuse-db
; Tras cambiar modelos/migraciones, recrear la BD de test: pytest --create-db
