# Generated by Django 5.2.16 on 2026-07-29 18:46
"""Separa el token de CONFIRMACIÓN (caduca, un solo uso) del de BAJA (permanente).

Hasta ahora un único `token` servía para ambas cosas y no caducaba nunca (hallazgo
S-15). Se añade `confirm_token`, y una migración de datos copia el valor actual a los
suscriptores PENDIENTES para que los enlaces de confirmación ya enviados sigan
funcionando tras el despliegue (con una ventana nueva de 48 h).
"""

from django.db import migrations, models
from django.utils import timezone


def portar_tokens_pendientes(apps, schema_editor):
    Subscriber = apps.get_model("community", "NewsletterSubscriber")
    Subscriber.objects.filter(status="pending").exclude(token="").update(
        confirm_token=models.F("token"), confirm_token_at=timezone.now()
    )


def revertir(apps, schema_editor):
    # Los campos se eliminan al revertir; no hay nada que deshacer en los datos.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirm_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirm_token_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.RunPython(portar_tokens_pendientes, revertir),
    ]
