# Generated by Django 5.1.15 on 2026-07-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_recording'),
        ('people', '0002_contributor_active_contributor_is_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'hito',
                'verbose_name_plural': 'hitos',
                'ordering': ['-year', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('recital', 'Recital'), ('lanzamiento', 'Lanzamiento'), ('taller', 'Taller'), ('festival', 'Festival'), ('feria', 'Feria'), ('otro', 'Otro')], default='recital', max_length=20)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, help_text='Lugar (sala, café…).', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_external', models.BooleanField(default=False, help_text='Participación en un evento organizado por terceros.')),
                ('host', models.CharField(blank=True, help_text='Organizador externo (si aplica).', max_length=255)),
                ('registration_url', models.URLField(blank=True, help_text='Inscripción o entradas.')),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to='people.contributor')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, help_text='Pie de foto (si difiere del recurso).', max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.mediaasset')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='agenda.event')),
            ],
            options={
                'verbose_name': 'foto de evento',
                'verbose_name_plural': 'fotos de evento',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'asset'), name='uniq_event_asset')],
            },
        ),
    ]
