# Generated by Django 5.1.15 on 2026-07-27 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_editorial_generic_finalize'),
        ('media', '0002_recording'),
        ('people', '0002_contributor_active_contributor_is_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios pedidos'), ('approved', 'Aprobado'), ('scheduled', 'Programado'), ('published', 'Publicado'), ('archived', 'Archivado'), ('rejected', 'Rechazado')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('epigraph', models.TextField(blank=True, help_text='Epígrafe o dedicatoria (opcional).')),
                ('body', models.TextField(help_text='Texto plano: se preservan saltos de línea y sangrías.')),
                ('featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(blank=True, help_text='Registro del poema leído por su autor/a (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poems', to='media.recording')),
            ],
            options={
                'verbose_name': 'poema',
                'verbose_name_plural': 'poemas',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPoem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.collection')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.poem')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='poems',
            field=models.ManyToManyField(blank=True, related_name='collections', through='content.CollectionPoem', to='content.poem'),
        ),
        migrations.CreateModel(
            name='PoemContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.contributor')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.poem')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='poem',
            name='authors',
            field=models.ManyToManyField(related_name='poems', through='content.PoemContributor', to='people.contributor'),
        ),
        migrations.AddConstraint(
            model_name='collectionpoem',
            constraint=models.UniqueConstraint(fields=('collection', 'poem'), name='uniq_collection_poem'),
        ),
        migrations.AddConstraint(
            model_name='poemcontributor',
            constraint=models.UniqueConstraint(fields=('poem', 'contributor'), name='uniq_poem_contributor'),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=models.Index(fields=['status', '-published_at'], name='poem_status_pub_idx'),
        ),
    ]
