# Generated by Django 5.2.16 on 2026-07-28 14:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_legal_pages'),
        ('media', '0003_recording_event'),
        ('people', '0002_contributor_active_contributor_is_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='poem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='poem_search_gin'),
        ),
    ]
