# Generated by Django 5.2.17 on 2026-09-02 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_unaccent_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecontributor',
            options={'ordering': ['position'], 'verbose_name': 'autoría de artículo', 'verbose_name_plural': 'autorías de artículo'},
        ),
        migrations.AlterModelOptions(
            name='collectionarticle',
            options={'ordering': ['position'], 'verbose_name': 'artículo de la colección', 'verbose_name_plural': 'artículos de la colección'},
        ),
        migrations.AlterModelOptions(
            name='collectionpoem',
            options={'ordering': ['position'], 'verbose_name': 'poema de la colección', 'verbose_name_plural': 'poemas de la colección'},
        ),
        migrations.AlterModelOptions(
            name='editorialnote',
            options={'ordering': ['created_at'], 'verbose_name': 'nota editorial', 'verbose_name_plural': 'notas editoriales'},
        ),
        migrations.AlterModelOptions(
            name='editorialtransition',
            options={'ordering': ['-created_at'], 'verbose_name': 'transición editorial', 'verbose_name_plural': 'transiciones editoriales'},
        ),
        migrations.AlterModelOptions(
            name='poemcontributor',
            options={'ordering': ['position'], 'verbose_name': 'autoría de poema', 'verbose_name_plural': 'autorías de poema'},
        ),
        migrations.AlterModelOptions(
            name='reviewedwork',
            options={'verbose_name': 'obra reseñada', 'verbose_name_plural': 'obras reseñadas'},
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dueño'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='editorialtransition',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_transitions', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='editorialtransition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='editorialtransition',
            name='from_status',
            field=models.CharField(max_length=20, verbose_name='estado de origen'),
        ),
        migrations.AlterField(
            model_name='editorialtransition',
            name='note',
            field=models.TextField(blank=True, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='editorialtransition',
            name='to_status',
            field=models.CharField(max_length=20, verbose_name='estado de destino'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dueño'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
    ]
