# Generated by Django 5.1.15 on 2026-07-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Colectivo', max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Poética corta / lema.', max_length=255)),
                ('manifesto', models.TextField(blank=True, help_text='Manifiesto o poética del colectivo.')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Ciudad / comuna.', max_length=255)),
                ('general_email', models.EmailField(blank=True, max_length=254)),
                ('booking_email', models.EmailField(blank=True, help_text='Contacto de gestión / contrataciones (prensa, programación).', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('dossier_pdf', models.FileField(blank=True, help_text='PDF del kit de prensa (override manual opcional del dossier generado).', upload_to='dossier/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.recording')),
            ],
            options={
                'verbose_name': 'perfil del sitio',
                'verbose_name_plural': 'perfil del sitio',
            },
        ),
        migrations.CreateModel(
            name='SiteSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='showcase.siteprofile')),
            ],
            options={
                'ordering': ['position', 'platform'],
            },
        ),
    ]
