# Generated by Django 5.1.15 on 2026-07-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_article_owner_poem_collectionpoem_and_more'),
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='featured_poem',
            field=models.ForeignKey(blank=True, help_text='Poema destacado en la portada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.poem'),
        ),
    ]
