# Generated by Django 5.1.15 on 2026-07-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_recording_event'),
        ('people', '0002_contributor_active_contributor_is_member_and_more'),
        ('reviews', '0001_initial'),
        ('showcase', '0002_siteprofile_featured_poem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('financiamiento', 'Financiamiento'), ('institucion', 'Institución'), ('editorial', 'Editorial'), ('medio', 'Medio'), ('espacio', 'Espacio'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
            ],
            options={
                'verbose_name': 'aliado',
                'verbose_name_plural': 'aliados',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PressMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('outlet', models.CharField(help_text='Medio (diario, revista, radio…).', max_length=255)),
                ('author', models.CharField(blank=True, help_text='Periodista (opcional).', max_length=255)),
                ('kind', models.CharField(choices=[('entrevista', 'Entrevista'), ('resena', 'Reseña'), ('nota', 'Nota'), ('perfil', 'Perfil'), ('mencion', 'Mención')], default='nota', max_length=20)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('quote', models.TextField(blank=True, help_text='Cita destacada para portada y dossier.')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
            ],
            options={
                'verbose_name': 'mención en prensa',
                'verbose_name_plural': 'menciones en prensa',
                'ordering': ['position', '-published_on'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('libro', 'Libro'), ('plaquette', 'Plaquette'), ('fanzine', 'Fanzine'), ('antologia', 'Antología'), ('revista', 'Revista'), ('disco', 'Disco')], default='plaquette', max_length=20)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('synopsis', models.TextField(blank=True)),
                ('is_own', models.BooleanField(default=True, help_text='Editada por el colectivo (vs participación en obra ajena).')),
                ('pdf', models.FileField(blank=True, help_text='PDF de descarga gratuita (plaquettes/fanzines digitales).', upload_to='publications/')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('participants', models.ManyToManyField(blank=True, related_name='publications', to='people.contributor')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reviews.publisher')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['position', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WhereToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Editorial / feria / librería.', max_length=120)),
                ('url', models.URLField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_to_buy', to='showcase.publication')),
            ],
            options={
                'verbose_name': 'punto de venta',
                'verbose_name_plural': 'puntos de venta',
                'ordering': ['position', 'label'],
            },
        ),
    ]
