# Generated by Django 5.2.16 on 2026-07-28 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_recording_recording_file_or_embed'),
        ('showcase', '0004_ensure_siteprofile_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Imagen social por defecto (og:image) y logo en los datos estructurados.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset'),
        ),
    ]
