# Generated by Django 5.2.16 on 2026-07-29 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_siteprofile_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, help_text='PDF de descarga gratuita (plaquettes/fanzines digitales).', upload_to='publications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se admite PDF (%(allowed_extensions)s).')]),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='dossier_pdf',
            field=models.FileField(blank=True, help_text='PDF del kit de prensa (override manual opcional del dossier generado).', upload_to='dossier/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se admite PDF (%(allowed_extensions)s).')]),
        ),
    ]
