# Generated by Django 5.2.17 on 2026-09-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_publication_pdf_alter_siteprofile_dossier_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesociallink',
            options={'ordering': ['position', 'platform'], 'verbose_name': 'red social del sitio', 'verbose_name_plural': 'redes sociales del sitio'},
        ),
    ]
