# Generated by Django 5.1.15 on 2026-07-09 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'convocatoria',
                'verbose_name_plural': 'convocatorias',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='submissions/%Y/%m/')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('in_review', 'En revisión'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado')], db_index=True, default='received', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='submissions.call')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'envío',
                'verbose_name_plural': 'envíos',
                'ordering': ['-created_at'],
            },
        ),
    ]
