# Generated by Django 5.1.15 on 2026-07-09 18:41

import apps.submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, storage=apps.submissions.models.private_storage, upload_to='submissions/%Y/%m/'),
        ),
    ]
