# Generated by Django 5.1.15 on 2026-07-09 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(height_field='height', upload_to='assets/%Y/%m/', width_field='width')),
                ('alt_text', models.CharField(help_text='Texto alternativo. Obligatorio por accesibilidad y SEO.', max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
