# Generated by Django 5.1.15 on 2026-07-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='video', max_length=10)),
                ('file', models.FileField(blank=True, upload_to='recordings/%Y/%m/')),
                ('embed_url', models.URLField(blank=True, help_text='URL de YouTube/Vimeo/SoundCloud/Bandcamp (alternativa al archivo).')),
                ('description', models.TextField(blank=True)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='recordings', to='people.contributor')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['position', '-recorded_on', '-created_at'],
            },
        ),
    ]
