# Generated by Django 5.1.15 on 2026-07-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('media', '0002_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Evento del que proviene el registro (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='agenda.event'),
        ),
    ]
