# Generated by Django 5.2.16 on 2026-07-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('media', '0003_recording_event'),
        ('people', '0002_contributor_active_contributor_is_member_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.CheckConstraint(condition=models.Q(('file', ''), ('embed_url', ''), _negated=True), name='recording_file_or_embed'),
        ),
    ]
