# Generated by Django 5.2.16 on 2026-07-29 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_recording_recording_file_or_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(blank=True, upload_to='recordings/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a', 'oga', 'ogg', 'opus', 'wav', 'flac', 'mp4', 'm4v', 'webm'], message='Formato no permitido. Usa audio o vídeo: %(allowed_extensions)s. Nunca se aceptan archivos que el navegador pueda ejecutar (.html, .svg…).')]),
        ),
    ]
