# Generated by Django 5.2.16 on 2026-07-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_recording_recording_file_or_embed'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn__isnull', False), models.Q(('isbn', ''), _negated=True)), fields=('isbn',), name='uniq_work_isbn'),
        ),
    ]
