# Generated by Django 5.1.15 on 2026-07-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='active',
            field=models.BooleanField(default=True, help_text='Integrante activo; desmarcado = histórico.'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='is_member',
            field=models.BooleanField(default=False, help_text='Integrante del colectivo (aparece en /integrantes/).'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='member_since',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Año de ingreso al colectivo.', null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='poetics',
            field=models.TextField(blank=True, help_text='Poética personal (declaración breve).'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden en la grilla de integrantes.'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.CharField(blank=True, help_text='Rol en el colectivo (p. ej. «fundadora», «gestión»).', max_length=100),
        ),
        migrations.AddField(
            model_name='contributor',
            name='short_bio',
            field=models.CharField(blank=True, help_text='Bio breve para tarjetas y dossier (1–2 frases).', max_length=280),
        ),
    ]
