# Generated by Django 5.2.17 on 2026-09-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_contributor_active_contributor_is_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['position'], 'verbose_name': 'red social', 'verbose_name_plural': 'redes sociales'},
        ),
    ]
